### ISSUE TITLE
Stuck refering to magic tac in pods shortcode within template

### ISSUE THREAD

**Issue by oldrup** [pods-framework/pods-support#12]
Hey. I'm stuck in a logical/syntax pit, wondering if any of you could point me in the right direction.

Creating a template for a CPT **Adresse**, I'm referencing the field **adresseid**, and I want to fetch all **materiel** from another CPT, with that **adresseid**. If use a pods shortcode in the template, with a fixed id (in this case 56329), things works as expected, but if I attempt to use the magic tag {@adresseid} instead, it does not work.

Snippet of my template with fixed and variable id below:

`
<h2>AdresseID (eg 56329):{@adresseid}</h2>

<h3>Pods shortcode with fixed adresseid works:</h3>
[pods name="materiel" limit="20" where="adresseid.meta_value=56329" template="Materiel" shortcodes=1]

<h3>Pods shortcode referencing magic tag does not work:</h3>
[pods name="materiel" limit="20" where="adresseid.meta_value={@adresseid}" template="Materiel" shortcodes=1]
`

Any suggestions? The themes I expect to use, would allow me to insert a piece of PHP code instead, if that would make things easier, but I've have very limited knowledge on PHP and I have only got a few days to get this to work..

Any help would be greatly appreciated

**Comment by jimtrue** [comment]
@oldrup This is not the appropriate place to reach out for support

Please check our website at https://support.pods.io You can open tickets through our forums at WordPress.org or on our Slack Chat.
